import { readFileSync, writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));

interface ToolEntry {
  slug: string;
  name: string;
  shortDescription: string;
  githubUrl: string;
  stars: number;
  categories: string[];
  securityScore: number | null;
}

function main() {
  const seedPath = resolve(__dirname, '../apps/registry-api/src/validated-seed.json');
  const tools: ToolEntry[] = JSON.parse(readFileSync(seedPath, 'utf-8'));

  const sorted = [...tools].sort((a, b) => b.stars - a.stars);
  const categoryMap = new Map<string, ToolEntry[]>();

  for (const tool of sorted) {
    const cats = tool.categories && tool.categories.length > 0
      ? tool.categories
      : ['uncategorized'];
    for (const cat of cats) {
      if (!categoryMap.has(cat)) categoryMap.set(cat, []);
      const list = categoryMap.get(cat)!;
      if (list.length < 20 && !list.find(t => t.slug === tool.slug)) {
        list.push(tool);
      }
    }
  }

  const categoryOrder = [
    'ai', 'developer-tools', 'database', 'browser-automation', 'web',
    'security', 'infrastructure', 'cloud', 'framework', 'memory',
    'testing', 'productivity', 'monitoring', 'communication', 'finance',
    'design', 'filesystem', 'analytics', 'crm', 'uncategorized',
  ];

  let md = `# MCPub Registry — ${tools.length} Verified MCP Servers

> Curated by [MCPub](https://mcpub-web.vercel.app) — the npm for AI tools.
> Install any tool: \`npx mcpub install <slug>\`
> Last updated: ${new Date().toISOString().split('T')[0]}

## Contents

`;

  for (const category of categoryOrder) {
    const list = categoryMap.get(category);
    if (!list) continue;
    const totalInCategory = tools.filter(t => t.categories?.includes(category)).length;
    const anchor = category.toLowerCase().replace(/\s+/g, '-');
    md += `- [${formatCategoryName(category)} (${totalInCategory})](#${anchor})\n`;
  }

  md += '\n---\n\n';

  for (const category of categoryOrder) {
    const list = categoryMap.get(category);
    if (!list) continue;
    const totalInCategory = tools.filter(t => t.categories?.includes(category)).length;

    const anchor = category.toLowerCase().replace(/\s+/g, '-');
    md += `## ${formatCategoryName(category)}\n\n`;
    md += `> ${totalInCategory} tools total. Showing top ${Math.min(20, list.length)} by stars.\n\n`;

    md += '| Tool | Stars | Description | Install |\n';
    md += '|------|-------|-------------|--------|\n';

    for (const tool of list) {
      const desc = truncate(tool.shortDescription, 80);
      const stars = tool.stars >= 1000
        ? `⭐ ${(tool.stars / 1000).toFixed(tool.stars >= 10000 ? 0 : 1)}k`
        : `⭐ ${tool.stars}`;
      md += `| [${tool.slug}](${tool.githubUrl}) | ${stars} | ${desc} | \`npx mcpub install ${tool.slug}\` |\n`;
    }

    if (totalInCategory > 20) {
      md += `\n_... and [${totalInCategory - 20} more](${encodeURI(`https://mcpub-web.vercel.app/search?q=${category}`)})._`;
    }

    md += '\n\n';
  }

  const footer = `---
Generated by [MCPub](https://mcpub-web.vercel.app) on ${new Date().toISOString().split('T')[0]}.
`;

  md += footer;

  const outputPath = resolve(__dirname, '../REGISTRY.md');
  writeFileSync(outputPath, md, 'utf-8');
  console.log(`✅ REGISTRY.md written (${md.length} bytes, ${tools.length} tools, ${categoryMap.size} categories)`);
}

function formatCategoryName(cat: string): string {
  return cat.charAt(0).toUpperCase() + cat.slice(1).replace(/-/g, ' ');
}

function truncate(s: string, maxLen: number): string {
  if (s.length <= maxLen) return s;
  const truncated = s.slice(0, maxLen);
  const lastSpace = truncated.lastIndexOf(' ');
  return (lastSpace > 0 ? truncated.slice(0, lastSpace) : truncated) + '...';
}

main();
