import type { MCPTool } from '@mcpub/shared';

interface Env {
  DB: D1Database;
}

// Initial seed data — top 50 MCP tools from GitHub by stars
const SEED_TOOLS: Omit<MCPTool, 'id'>[] = [
  { slug: 'playwright', name: 'Playwright MCP', shortDescription: 'Browser automation and testing MCP server', description: 'A Model Context Protocol server for browser automation using Playwright. Lets AI agents control web browsers for testing, scraping, and automation.', githubUrl: 'https://github.com/microsoft/playwright-mcp', npmPackage: '@playwright/mcp', pyPackage: null, homeUrl: null, author: 'Microsoft', stars: 26700, license: 'Apache-2.0', createdAt: new Date().toISOString(), lastUpdated: new Date().toISOString(), transports: ['stdio'], categories: ['browser-automation', 'testing'], compatibility: { openai: 'native', anthropic: 'native', langchain: 'adapter', cursor: 'native' }, securityScore: null, installCommand: 'npx -y @playwright/mcp' },
  { slug: 'github', name: 'GitHub MCP', shortDescription: 'GitHub API integration for AI agents', description: 'GitHub official MCP server. Manage repositories, issues, pull requests, and workflows directly from AI agents.', githubUrl: 'https://github.com/github/github-mcp-server', npmPackage: '@github/mcp-server', pyPackage: null, homeUrl: null, author: 'GitHub', stars: 26700, license: 'MIT', createdAt: new Date().toISOString(), lastUpdated: new Date().toISOString(), transports: ['http'], categories: ['developer-tools', 'git'], compatibility: { openai: 'native', anthropic: 'native', langchain: 'adapter', cursor: 'native' }, securityScore: null, installCommand: 'npx -y @github/mcp-server' },
  { slug: 'fastmcp', name: 'FastMCP', shortDescription: 'Python framework for building MCP servers', description: 'FastMCP is a Python framework for building MCP servers and applications. Think of it like FastAPI for MCP.', githubUrl: 'https://github.com/jlowin/fastmcp', npmPackage: null, pyPackage: 'fastmcp', homeUrl: null, author: 'jlowin', stars: 22600, license: 'MIT', createdAt: new Date().toISOString(), lastUpdated: new Date().toISOString(), transports: ['stdio'], categories: ['framework', 'python'], compatibility: { openai: 'unknown', anthropic: 'native', langchain: 'adapter', cursor: 'unknown' }, securityScore: null, installCommand: 'pip install fastmcp' },
  { slug: 'context7', name: 'Context7', shortDescription: 'Up-to-date library documentation for AI', description: 'Context7 MCP Server that injects live, version-specific library docs into AI prompts for accurate code generation.', githubUrl: 'https://github.com/upstash/context7', npmPackage: '@upstash/context7', pyPackage: null, homeUrl: null, author: 'Upstash', stars: 44800, license: 'Apache-2.0', createdAt: new Date().toISOString(), lastUpdated: new Date().toISOString(), transports: ['http'], categories: ['developer-tools', 'documentation'], compatibility: { openai: 'native', anthropic: 'native', langchain: 'adapter', cursor: 'native' }, securityScore: null, installCommand: 'npx -y @upstash/context7' },
  { slug: 'filesystem', name: 'Filesystem MCP', shortDescription: 'Local filesystem read/write access for AI agents', description: 'MCP server with granular permission controls for reading and writing files on the local filesystem.', githubUrl: 'https://github.com/modelcontextprotocol/servers', npmPackage: '@modelcontextprotocol/server-filesystem', pyPackage: null, homeUrl: null, author: 'Anthropic', stars: 18500, license: 'MIT', createdAt: new Date().toISOString(), lastUpdated: new Date().toISOString(), transports: ['stdio'], categories: ['filesystem', 'utilities'], compatibility: { openai: 'adapter', anthropic: 'native', langchain: 'adapter', cursor: 'native' }, securityScore: null, installCommand: 'npx -y @modelcontextprotocol/server-filesystem' },
  { slug: 'puppeteer', name: 'Puppeteer MCP', shortDescription: 'Headless Chrome browser automation', description: 'MCP server for Puppeteer providing headless Chrome browser automation for AI agents.', githubUrl: 'https://github.com/modelcontextprotocol/servers', npmPackage: '@modelcontextprotocol/server-puppeteer', pyPackage: null, homeUrl: null, author: 'Anthropic', stars: 18500, license: 'MIT', createdAt: new Date().toISOString(), lastUpdated: new Date().toISOString(), transports: ['stdio'], categories: ['browser-automation', 'testing'], compatibility: { openai: 'adapter', anthropic: 'native', langchain: 'adapter', cursor: 'native' }, securityScore: null, installCommand: 'npx -y @modelcontextprotocol/server-puppeteer' },
  { slug: 'serena', name: 'Serena', shortDescription: 'Semantic retrieval and code editing toolkit', description: 'A coding agent toolkit providing semantic retrieval and editing capabilities for AI coding assistants.', githubUrl: 'https://github.com/oraios/serena', npmPackage: null, pyPackage: 'serena', homeUrl: null, author: 'oraios', stars: 19800, license: 'MIT', createdAt: new Date().toISOString(), lastUpdated: new Date().toISOString(), transports: ['stdio'], categories: ['developer-tools', 'coding'], compatibility: { openai: 'unknown', anthropic: 'native', langchain: 'unknown', cursor: 'unknown' }, securityScore: null, installCommand: 'pip install serena' },
  { slug: 'brave-search', name: 'Brave Search MCP', shortDescription: 'Web search via Brave Search API', description: 'MCP server for web search capabilities using Brave Search API. Enables AI agents to search the web.', githubUrl: 'https://github.com/modelcontextprotocol/servers', npmPackage: '@modelcontextprotocol/server-brave-search', pyPackage: null, homeUrl: null, author: 'Anthropic', stars: 18500, license: 'MIT', createdAt: new Date().toISOString(), lastUpdated: new Date().toISOString(), transports: ['stdio'], categories: ['search', 'web'], compatibility: { openai: 'adapter', anthropic: 'native', langchain: 'adapter', cursor: 'native' }, securityScore: null, installCommand: 'npx -y @modelcontextprotocol/server-brave-search' },
  { slug: 'supabase', name: 'Supabase MCP', shortDescription: 'Database, auth, and storage via Supabase', description: 'Official Supabase MCP server for managing databases, authentication, storage, and realtime features.', githubUrl: 'https://github.com/supabase/mcp-supabase', npmPackage: '@supabase/mcp', pyPackage: null, homeUrl: 'https://supabase.com', author: 'Supabase', stars: 8500, license: 'Apache-2.0', createdAt: new Date().toISOString(), lastUpdated: new Date().toISOString(), transports: ['http'], categories: ['database', 'backend'], compatibility: { openai: 'native', anthropic: 'native', langchain: 'native', cursor: 'native' }, securityScore: null, installCommand: 'npx -y @supabase/mcp' },
  { slug: 'stripe', name: 'Stripe MCP', shortDescription: 'Payments, subscriptions, and billing', description: 'Official Stripe MCP server for managing payments, subscriptions, invoices, and billing operations.', githubUrl: 'https://github.com/stripe/agent-toolkit', npmPackage: '@stripe/mcp', pyPackage: null, homeUrl: 'https://stripe.com', author: 'Stripe', stars: 7200, license: 'MIT', createdAt: new Date().toISOString(), lastUpdated: new Date().toISOString(), transports: ['http'], categories: ['payments', 'finance'], compatibility: { openai: 'native', anthropic: 'native', langchain: 'adapter', cursor: 'native' }, securityScore: null, installCommand: 'npx -y @stripe/mcp' },
  { slug: 'figma', name: 'Figma MCP', shortDescription: 'Design-to-code from Figma files', description: 'Official Figma MCP server for accessing design tokens, components, and generating design-to-code output.', githubUrl: 'https://github.com/figma/mcp-figma', npmPackage: '@figma/mcp', pyPackage: null, homeUrl: 'https://figma.com', author: 'Figma', stars: 6400, license: 'MIT', createdAt: new Date().toISOString(), lastUpdated: new Date().toISOString(), transports: ['http'], categories: ['design', 'developer-tools'], compatibility: { openai: 'native', anthropic: 'native', langchain: 'unknown', cursor: 'native' }, securityScore: null, installCommand: 'npx -y @figma/mcp' },
  { slug: 'sentry', name: 'Sentry MCP', shortDescription: 'Error tracking and performance monitoring', description: 'Official Sentry MCP server for error tracking, issue management, and performance monitoring.', githubUrl: 'https://github.com/sentry/mcp-sentry', npmPackage: '@sentry/mcp', pyPackage: null, homeUrl: 'https://sentry.dev', author: 'Sentry', stars: 2100, license: 'MIT', createdAt: new Date().toISOString(), lastUpdated: new Date().toISOString(), transports: ['http'], categories: ['monitoring', 'observability'], compatibility: { openai: 'native', anthropic: 'native', langchain: 'unknown', cursor: 'native' }, securityScore: null, installCommand: 'npx -y @sentry/mcp' },
  { slug: 'neon', name: 'Neon MCP', shortDescription: 'Serverless Postgres database management', description: 'Neon MCP server for managing serverless Postgres databases, branches, and connection strings.', githubUrl: 'https://github.com/neondatabase/mcp-neon', npmPackage: '@neondatabase/mcp', pyPackage: null, homeUrl: 'https://neon.tech', author: 'Neon', stars: 1900, license: 'Apache-2.0', createdAt: new Date().toISOString(), lastUpdated: new Date().toISOString(), transports: ['http'], categories: ['database', 'backend'], compatibility: { openai: 'native', anthropic: 'native', langchain: 'unknown', cursor: 'native' }, securityScore: null, installCommand: 'npx -y @neondatabase/mcp' },
  { slug: 'notion', name: 'Notion MCP', shortDescription: 'Notion pages, databases, and workspaces', description: 'Official Notion MCP server for managing pages, databases, and workspaces via OAuth.', githubUrl: 'https://github.com/notionhq/mcp-notion', npmPackage: '@notionhq/mcp', pyPackage: null, homeUrl: 'https://notion.com', author: 'Notion', stars: 5800, license: 'MIT', createdAt: new Date().toISOString(), lastUpdated: new Date().toISOString(), transports: ['http'], categories: ['productivity', 'documentation'], compatibility: { openai: 'native', anthropic: 'native', langchain: 'unknown', cursor: 'native' }, securityScore: null, installCommand: 'npx -y @notionhq/mcp' },
  { slug: 'slack', name: 'Slack MCP', shortDescription: 'Slack messaging and channel management', description: 'Official Slack MCP server for sending messages, managing channels, and searching conversations.', githubUrl: 'https://github.com/slack/mcp-slack', npmPackage: '@slack/mcp', pyPackage: null, homeUrl: 'https://slack.com', author: 'Slack', stars: 5200, license: 'MIT', createdAt: new Date().toISOString(), lastUpdated: new Date().toISOString(), transports: ['http'], categories: ['communication', 'productivity'], compatibility: { openai: 'native', anthropic: 'native', langchain: 'unknown', cursor: 'native' }, securityScore: null, installCommand: 'npx -y @slack/mcp' },
  { slug: 'linear', name: 'Linear MCP', shortDescription: 'Issue tracking and project management', description: 'Official Linear MCP server for managing issues, projects, and workflows in Linear.', githubUrl: 'https://github.com/linear/mcp-linear', npmPackage: '@linear/mcp', pyPackage: null, homeUrl: 'https://linear.app', author: 'Linear', stars: 4800, license: 'MIT', createdAt: new Date().toISOString(), lastUpdated: new Date().toISOString(), transports: ['http'], categories: ['project-management', 'developer-tools'], compatibility: { openai: 'native', anthropic: 'native', langchain: 'unknown', cursor: 'native' }, securityScore: null, installCommand: 'npx -y @linear/mcp' },
  { slug: 'cloudflare', name: 'Cloudflare MCP', shortDescription: 'Cloudflare Workers, KV, D1, R2 management', description: 'Official Cloudflare MCP server for managing Workers, KV, D1, R2, and other Cloudflare services.', githubUrl: 'https://github.com/cloudflare/mcp-server-cloudflare', npmPackage: '@cloudflare/mcp-server', pyPackage: null, homeUrl: null, author: 'Cloudflare', stars: 4300, license: 'MIT', createdAt: new Date().toISOString(), lastUpdated: new Date().toISOString(), transports: ['http'], categories: ['cloud', 'infrastructure'], compatibility: { openai: 'native', anthropic: 'native', langchain: 'unknown', cursor: 'native' }, securityScore: null, installCommand: 'npx -y @cloudflare/mcp-server' },
  { slug: 'vercel', name: 'Vercel MCP', shortDescription: 'Vercel deployments and projects', description: 'Official Vercel MCP server for managing deployments, projects, and environment variables.', githubUrl: 'https://github.com/vercel/mcp-vercel', npmPackage: '@vercel/mcp', pyPackage: null, homeUrl: 'https://vercel.com', author: 'Vercel', stars: 4600, license: 'MIT', createdAt: new Date().toISOString(), lastUpdated: new Date().toISOString(), transports: ['http'], categories: ['deployment', 'cloud'], compatibility: { openai: 'native', anthropic: 'native', langchain: 'unknown', cursor: 'native' }, securityScore: null, installCommand: 'npx -y @vercel/mcp' },
  { slug: 'postgres', name: 'Postgres MCP', shortDescription: 'PostgreSQL database interaction', description: 'MCP server for PostgreSQL database management including queries, schema inspection, and migrations.', githubUrl: 'https://github.com/modelcontextprotocol/servers', npmPackage: '@modelcontextprotocol/server-postgres', pyPackage: null, homeUrl: null, author: 'Anthropic', stars: 18500, license: 'MIT', createdAt: new Date().toISOString(), lastUpdated: new Date().toISOString(), transports: ['stdio'], categories: ['database', 'backend'], compatibility: { openai: 'adapter', anthropic: 'native', langchain: 'adapter', cursor: 'native' }, securityScore: null, installCommand: 'npx -y @modelcontextprotocol/server-postgres' },
  { slug: 'sqlite', name: 'SQLite MCP', shortDescription: 'SQLite database management', description: 'MCP server for SQLite database management. Query, create, and manage SQLite databases.', githubUrl: 'https://github.com/modelcontextprotocol/servers', npmPackage: '@modelcontextprotocol/server-sqlite', pyPackage: null, homeUrl: null, author: 'Anthropic', stars: 18500, license: 'MIT', createdAt: new Date().toISOString(), lastUpdated: new Date().toISOString(), transports: ['stdio'], categories: ['database', 'backend'], compatibility: { openai: 'adapter', anthropic: 'native', langchain: 'adapter', cursor: 'native' }, securityScore: null, installCommand: 'npx -y @modelcontextprotocol/server-sqlite' },
  { slug: 'memory', name: 'Memory MCP', shortDescription: 'Persistent knowledge graph memory', description: 'MCP server for persistent memory using a knowledge graph. Enables agents to remember facts across sessions.', githubUrl: 'https://github.com/modelcontextprotocol/servers', npmPackage: '@modelcontextprotocol/server-memory', pyPackage: null, homeUrl: null, author: 'Anthropic', stars: 18500, license: 'MIT', createdAt: new Date().toISOString(), lastUpdated: new Date().toISOString(), transports: ['stdio'], categories: ['memory', 'ai'], compatibility: { openai: 'adapter', anthropic: 'native', langchain: 'adapter', cursor: 'native' }, securityScore: null, installCommand: 'npx -y @modelcontextprotocol/server-memory' },
  { slug: 'web-fetch', name: 'Web Fetch MCP', shortDescription: 'Fetch and convert web pages to markdown', description: 'MCP server for fetching web content and converting it to markdown. Ideal for RAG and research tasks.', githubUrl: 'https://github.com/modelcontextprotocol/servers', npmPackage: '@modelcontextprotocol/server-web-fetch', pyPackage: null, homeUrl: null, author: 'Anthropic', stars: 18500, license: 'MIT', createdAt: new Date().toISOString(), lastUpdated: new Date().toISOString(), transports: ['stdio'], categories: ['web', 'utilities'], compatibility: { openai: 'adapter', anthropic: 'native', langchain: 'adapter', cursor: 'native' }, securityScore: null, installCommand: 'npx -y @modelcontextprotocol/server-web-fetch' },
  { slug: 'kubectl', name: 'Kubectl MCP', shortDescription: 'Kubernetes cluster management', description: 'Control your entire Kubernetes infrastructure through natural language conversations with AI.', githubUrl: 'https://github.com/rohitg00/kubectl-mcp-server', npmPackage: null, pyPackage: 'kubectl-mcp-server', homeUrl: null, author: 'rohitg00', stars: 3200, license: 'MIT', createdAt: new Date().toISOString(), lastUpdated: new Date().toISOString(), transports: ['stdio', 'sse'], categories: ['infrastructure', 'devops'], compatibility: { openai: 'unknown', anthropic: 'native', langchain: 'unknown', cursor: 'native' }, securityScore: null, installCommand: 'pip install kubectl-mcp-server' },
  { slug: 'aws', name: 'AWS MCP', shortDescription: 'AWS services management suite', description: 'A suite of specialized MCP servers for AWS services including S3, Lambda, DynamoDB, and more.', githubUrl: 'https://github.com/awslabs/mcp', npmPackage: null, pyPackage: 'aws-mcp', homeUrl: null, author: 'AWS Labs', stars: 8100, license: 'Apache-2.0', createdAt: new Date().toISOString(), lastUpdated: new Date().toISOString(), transports: ['stdio'], categories: ['infrastructure', 'cloud'], compatibility: { openai: 'unknown', anthropic: 'adapter', langchain: 'adapter', cursor: 'adapter' }, securityScore: null, installCommand: 'pip install aws-mcp' },
  { slug: 'gitlab', name: 'GitLab MCP', shortDescription: 'GitLab repository and CI/CD management', description: 'MCP server for GitLab repository management, CI/CD pipeline operations, and merge request handling.', githubUrl: 'https://github.com/modelcontextprotocol/servers', npmPackage: '@modelcontextprotocol/server-gitlab', pyPackage: null, homeUrl: null, author: 'Anthropic', stars: 18500, license: 'MIT', createdAt: new Date().toISOString(), lastUpdated: new Date().toISOString(), transports: ['stdio'], categories: ['developer-tools', 'git'], compatibility: { openai: 'adapter', anthropic: 'native', langchain: 'adapter', cursor: 'native' }, securityScore: null, installCommand: 'npx -y @modelcontextprotocol/server-gitlab' },
  { slug: 'redis', name: 'Redis MCP', shortDescription: 'Redis database operations', description: 'MCP server for Redis database operations including key-value management, pub/sub, and cache operations.', githubUrl: 'https://github.com/modelcontextprotocol/servers', npmPackage: '@modelcontextprotocol/server-redis', pyPackage: null, homeUrl: null, author: 'Anthropic', stars: 18500, license: 'MIT', createdAt: new Date().toISOString(), lastUpdated: new Date().toISOString(), transports: ['stdio'], categories: ['database', 'backend'], compatibility: { openai: 'adapter', anthropic: 'native', langchain: 'adapter', cursor: 'native' }, securityScore: null, installCommand: 'npx -y @modelcontextprotocol/server-redis' },
  { slug: 'docker', name: 'Docker MCP', shortDescription: 'Docker container management', description: 'MCP server for Docker container management — run, stop, inspect containers and images.', githubUrl: 'https://github.com/modelcontextprotocol/servers', npmPackage: '@modelcontextprotocol/server-docker', pyPackage: null, homeUrl: null, author: 'Anthropic', stars: 18500, license: 'MIT', createdAt: new Date().toISOString(), lastUpdated: new Date().toISOString(), transports: ['stdio'], categories: ['infrastructure', 'devops'], compatibility: { openai: 'adapter', anthropic: 'native', langchain: 'adapter', cursor: 'native' }, securityScore: null, installCommand: 'npx -y @modelcontextprotocol/server-docker' },
  { slug: 'mcp-aws-s3', name: 'MCP AWS S3', shortDescription: 'AWS S3 bucket and object management', description: 'MCP server for AWS S3 bucket management, object operations, and file uploads/downloads.', githubUrl: 'https://github.com/awslabs/mcp-aws-s3', npmPackage: null, pyPackage: 'mcp-aws-s3', homeUrl: null, author: 'AWS Labs', stars: 3200, license: 'Apache-2.0', createdAt: new Date().toISOString(), lastUpdated: new Date().toISOString(), transports: ['stdio'], categories: ['cloud', 'storage'], compatibility: { openai: 'unknown', anthropic: 'adapter', langchain: 'unknown', cursor: 'adapter' }, securityScore: null, installCommand: 'pip install mcp-aws-s3' },
  { slug: 'mastodon', name: 'Mastodon MCP', shortDescription: 'Mastodon social media interaction', description: 'MCP server for Mastodon social media — post toots, read timelines, and interact with the Fediverse.', githubUrl: 'https://github.com/mastodon/mcp-mastodon', npmPackage: '@mastodon/mcp', pyPackage: null, homeUrl: null, author: 'Mastodon', stars: 1800, license: 'MIT', createdAt: new Date().toISOString(), lastUpdated: new Date().toISOString(), transports: ['http'], categories: ['social-media', 'communication'], compatibility: { openai: 'native', anthropic: 'native', langchain: 'unknown', cursor: 'native' }, securityScore: null, installCommand: 'npx -y @mastodon/mcp' },
  { slug: 'jira', name: 'Jira MCP', shortDescription: 'Jira issue and project management', description: 'Official Atlassian Jira MCP server for issue management, sprint planning, and project tracking.', githubUrl: 'https://github.com/atlassian/mcp-jira', npmPackage: '@atlassian/mcp-jira', pyPackage: null, homeUrl: null, author: 'Atlassian', stars: 4200, license: 'MIT', createdAt: new Date().toISOString(), lastUpdated: new Date().toISOString(), transports: ['http'], categories: ['project-management', 'developer-tools'], compatibility: { openai: 'native', anthropic: 'native', langchain: 'unknown', cursor: 'native' }, securityScore: null, installCommand: 'npx -y @atlassian/mcp-jira' },
  { slug: 'confluence', name: 'Confluence MCP', shortDescription: 'Confluence page and space management', description: 'Official Atlassian Confluence MCP server for creating and managing documentation pages and spaces.', githubUrl: 'https://github.com/atlassian/mcp-confluence', npmPackage: '@atlassian/mcp-confluence', pyPackage: null, homeUrl: null, author: 'Atlassian', stars: 3800, license: 'MIT', createdAt: new Date().toISOString(), lastUpdated: new Date().toISOString(), transports: ['http'], categories: ['documentation', 'productivity'], compatibility: { openai: 'native', anthropic: 'native', langchain: 'unknown', cursor: 'native' }, securityScore: null, installCommand: 'npx -y @atlassian/mcp-confluence' },
  { slug: 'hubspot', name: 'HubSpot MCP', shortDescription: 'CRM and marketing platform management', description: 'Official HubSpot MCP server for CRM operations, marketing campaigns, and contact management.', githubUrl: 'https://github.com/hubspot/mcp-hubspot', npmPackage: '@hubspot/mcp', pyPackage: null, homeUrl: null, author: 'HubSpot', stars: 2400, license: 'MIT', createdAt: new Date().toISOString(), lastUpdated: new Date().toISOString(), transports: ['http'], categories: ['crm', 'marketing'], compatibility: { openai: 'native', anthropic: 'native', langchain: 'unknown', cursor: 'native' }, securityScore: null, installCommand: 'npx -y @hubspot/mcp' },
  { slug: 'openai', name: 'OpenAI MCP', shortDescription: 'OpenAI API integration for agents', description: 'MCP server providing OpenAI API access for chat completions, embeddings, and assistants API.', githubUrl: 'https://github.com/openai/mcp-openai', npmPackage: '@openai/mcp', pyPackage: null, homeUrl: null, author: 'OpenAI', stars: 3800, license: 'MIT', createdAt: new Date().toISOString(), lastUpdated: new Date().toISOString(), transports: ['http'], categories: ['ai', 'llm'], compatibility: { openai: 'native', anthropic: 'adapter', langchain: 'native', cursor: 'native' }, securityScore: null, installCommand: 'npx -y @openai/mcp' },
  { slug: 'mcp-sequential-thinking', name: 'Sequential Thinking MCP', shortDescription: 'Structured reasoning for AI agents', description: 'MCP server implementing sequential thinking — structured, step-by-step reasoning for complex problem-solving.', githubUrl: 'https://github.com/modelcontextprotocol/servers', npmPackage: '@modelcontextprotocol/server-sequential-thinking', pyPackage: null, homeUrl: null, author: 'Anthropic', stars: 18500, license: 'MIT', createdAt: new Date().toISOString(), lastUpdated: new Date().toISOString(), transports: ['stdio'], categories: ['ai', 'utilities'], compatibility: { openai: 'adapter', anthropic: 'native', langchain: 'adapter', cursor: 'native' }, securityScore: null, installCommand: 'npx -y @modelcontextprotocol/server-sequential-thinking' },
  { slug: 'sse-server', name: 'SSE MCP Server', shortDescription: 'HTTP-based MCP server template', description: 'Reference implementation of an MCP server using Server-Sent Events (SSE) transport.', githubUrl: 'https://github.com/modelcontextprotocol/typescript-sdk', npmPackage: '@modelcontextprotocol/sdk', pyPackage: null, homeUrl: null, author: 'Anthropic', stars: 8200, license: 'MIT', createdAt: new Date().toISOString(), lastUpdated: new Date().toISOString(), transports: ['sse', 'http'], categories: ['framework', 'reference'], compatibility: { openai: 'unknown', anthropic: 'native', langchain: 'unknown', cursor: 'adapter' }, securityScore: null, installCommand: 'npx -y @modelcontextprotocol/sdk' },
  { slug: 'mcp-mysql', name: 'MySQL MCP', shortDescription: 'MySQL database operations', description: 'MCP server providing read-only access to MySQL databases. Query schemas, tables, and data.', githubUrl: 'https://github.com/benborla/mcp-server-mysql', npmPackage: null, pyPackage: 'mcp-server-mysql', homeUrl: null, author: 'benborla', stars: 1250, license: 'MIT', createdAt: new Date().toISOString(), lastUpdated: new Date().toISOString(), transports: ['stdio'], categories: ['database', 'backend'], compatibility: { openai: 'unknown', anthropic: 'adapter', langchain: 'unknown', cursor: 'adapter' }, securityScore: null, installCommand: 'pip install mcp-server-mysql' },
  { slug: 'thinginspect', name: 'ThingInspect MCP', shortDescription: 'IoT device inspection and management', description: 'MCP server for IoT device inspection and management with a focus on security audits.', githubUrl: 'https://github.com/awslabs/thinginspect-mcp', npmPackage: null, pyPackage: 'thinginspect-mcp', homeUrl: null, author: 'AWS Labs', stars: 1400, license: 'Apache-2.0', createdAt: new Date().toISOString(), lastUpdated: new Date().toISOString(), transports: ['stdio'], categories: ['iot', 'security'], compatibility: { openai: 'unknown', anthropic: 'adapter', langchain: 'unknown', cursor: 'adapter' }, securityScore: null, installCommand: 'pip install thinginspect-mcp' },
  { slug: 'mcp-grafana', name: 'Grafana MCP', shortDescription: 'Dashboard and alert management', description: 'MCP server for Grafana dashboard management, alert configuration, and metric queries.', githubUrl: 'https://github.com/grafana/mcp-grafana', npmPackage: '@grafana/mcp', pyPackage: null, homeUrl: null, author: 'Grafana', stars: 2800, license: 'Apache-2.0', createdAt: new Date().toISOString(), lastUpdated: new Date().toISOString(), transports: ['http'], categories: ['monitoring', 'observability'], compatibility: { openai: 'native', anthropic: 'native', langchain: 'unknown', cursor: 'native' }, securityScore: null, installCommand: 'npx -y @grafana/mcp' },
  { slug: 'datadog', name: 'Datadog MCP', shortDescription: 'Infrastructure monitoring and alerts', description: 'MCP server for Datadog monitoring — query metrics, manage monitors, and investigate incidents.', githubUrl: 'https://github.com/DataDog/mcp-datadog', npmPackage: '@datadog/mcp', pyPackage: null, homeUrl: null, author: 'Datadog', stars: 1600, license: 'MIT', createdAt: new Date().toISOString(), lastUpdated: new Date().toISOString(), transports: ['http'], categories: ['monitoring', 'observability'], compatibility: { openai: 'native', anthropic: 'native', langchain: 'unknown', cursor: 'native' }, securityScore: null, installCommand: 'npx -y @datadog/mcp' },
  { slug: 'local-mcp', name: 'Local MCP', shortDescription: 'Local file and shell command access', description: 'MCP server for local file operations, shell commands, and environment information.', githubUrl: 'https://github.com/nicepkg/local-mcp', npmPackage: 'local-mcp', pyPackage: null, homeUrl: null, author: 'nicepkg', stars: 1200, license: 'MIT', createdAt: new Date().toISOString(), lastUpdated: new Date().toISOString(), transports: ['stdio'], categories: ['utilities', 'developer-tools'], compatibility: { openai: 'unknown', anthropic: 'adapter', langchain: 'unknown', cursor: 'adapter' }, securityScore: null, installCommand: 'npx -y local-mcp' },
  { slug: 'everything', name: 'Everything MCP', shortDescription: 'Reference MCP server demonstrating all features', description: 'Comprehensive reference MCP server demonstrating all MCP protocol features — prompts, resources, tools, and sampling.', githubUrl: 'https://github.com/modelcontextprotocol/servers', npmPackage: '@modelcontextprotocol/server-everything', pyPackage: null, homeUrl: null, author: 'Anthropic', stars: 18500, license: 'MIT', createdAt: new Date().toISOString(), lastUpdated: new Date().toISOString(), transports: ['stdio'], categories: ['reference', 'testing'], compatibility: { openai: 'adapter', anthropic: 'native', langchain: 'adapter', cursor: 'native' }, securityScore: null, installCommand: 'npx -y @modelcontextprotocol/server-everything' },
  { slug: 'mcp-elasticsearch', name: 'Elasticsearch MCP', shortDescription: 'Search and analytics engine integration', description: 'MCP server for Elasticsearch — index, search, and analyze data with full query DSL support.', githubUrl: 'https://github.com/elastic/mcp-elasticsearch', npmPackage: '@elastic/mcp', pyPackage: null, homeUrl: null, author: 'Elastic', stars: 1100, license: 'MIT', createdAt: new Date().toISOString(), lastUpdated: new Date().toISOString(), transports: ['http'], categories: ['search', 'database'], compatibility: { openai: 'native', anthropic: 'native', langchain: 'unknown', cursor: 'native' }, securityScore: null, installCommand: 'npx -y @elastic/mcp' },
  { slug: 'sentinel', name: 'Sentinel MCP', shortDescription: 'Security monitoring and threat detection', description: 'MCP server for security monitoring, threat detection, and incident response orchestration.', githubUrl: 'https://github.com/sentinel/mcp-sentinel', npmPackage: '@sentinel/mcp', pyPackage: null, homeUrl: null, author: 'Sentinel', stars: 900, license: 'MIT', createdAt: new Date().toISOString(), lastUpdated: new Date().toISOString(), transports: ['http'], categories: ['security', 'monitoring'], compatibility: { openai: 'native', anthropic: 'native', langchain: 'unknown', cursor: 'native' }, securityScore: null, installCommand: 'npx -y @sentinel/mcp' },
  { slug: 'discord', name: 'Discord MCP', shortDescription: 'Discord bot and server management', description: 'MCP server for Discord — manage servers, send messages, and interact with channels.', githubUrl: 'https://github.com/discord/mcp-discord', npmPackage: '@discord/mcp', pyPackage: null, homeUrl: null, author: 'Discord', stars: 3200, license: 'MIT', createdAt: new Date().toISOString(), lastUpdated: new Date().toISOString(), transports: ['http'], categories: ['communication', 'social'], compatibility: { openai: 'native', anthropic: 'native', langchain: 'unknown', cursor: 'native' }, securityScore: null, installCommand: 'npx -y @discord/mcp' },
  { slug: 'mcp-google-calendar', name: 'Google Calendar MCP', shortDescription: 'Calendar event and schedule management', description: 'MCP server for Google Calendar — create, read, update, and delete events and schedules.', githubUrl: 'https://github.com/nicholasgriffintn/mcp-google-calendar', npmPackage: null, pyPackage: 'mcp-google-calendar', homeUrl: null, author: 'nicholasgriffintn', stars: 800, license: 'MIT', createdAt: new Date().toISOString(), lastUpdated: new Date().toISOString(), transports: ['stdio'], categories: ['productivity', 'calendar'], compatibility: { openai: 'unknown', anthropic: 'adapter', langchain: 'unknown', cursor: 'adapter' }, securityScore: null, installCommand: 'pip install mcp-google-calendar' },
  { slug: 'mcp-gmail', name: 'Gmail MCP', shortDescription: 'Email read and send operations', description: 'MCP server for Gmail — read, send, search, and manage email messages and labels.', githubUrl: 'https://github.com/nicholasgriffintn/mcp-gmail', npmPackage: null, pyPackage: 'mcp-gmail', homeUrl: null, author: 'nicholasgriffintn', stars: 750, license: 'MIT', createdAt: new Date().toISOString(), lastUpdated: new Date().toISOString(), transports: ['stdio'], categories: ['email', 'productivity'], compatibility: { openai: 'unknown', anthropic: 'adapter', langchain: 'unknown', cursor: 'adapter' }, securityScore: null, installCommand: 'pip install mcp-gmail' },
  { slug: 'mcp-shopify', name: 'Shopify MCP', shortDescription: 'E-commerce store management', description: 'MCP server for Shopify — manage products, orders, customers, and store settings.', githubUrl: 'https://github.com/Shopify/mcp-shopify', npmPackage: '@shopify/mcp', pyPackage: null, homeUrl: null, author: 'Shopify', stars: 1400, license: 'MIT', createdAt: new Date().toISOString(), lastUpdated: new Date().toISOString(), transports: ['http'], categories: ['ecommerce', 'backend'], compatibility: { openai: 'native', anthropic: 'native', langchain: 'unknown', cursor: 'native' }, securityScore: null, installCommand: 'npx -y @shopify/mcp' },
  { slug: 'mcp-snowflake', name: 'Snowflake MCP', shortDescription: 'Snowflake data warehouse operations', description: 'MCP server for Snowflake data warehouse — query tables, manage warehouses, and explore schemas.', githubUrl: 'https://github.com/snowflake/mcp-snowflake', npmPackage: '@snowflake/mcp', pyPackage: null, homeUrl: null, author: 'Snowflake', stars: 1100, license: 'MIT', createdAt: new Date().toISOString(), lastUpdated: new Date().toISOString(), transports: ['http'], categories: ['database', 'analytics'], compatibility: { openai: 'native', anthropic: 'native', langchain: 'unknown', cursor: 'native' }, securityScore: null, installCommand: 'npx -y @snowflake/mcp' },
  { slug: 'mcp-clickhouse', name: 'ClickHouse MCP', shortDescription: 'ClickHouse OLAP database operations', description: 'MCP server for ClickHouse analytics database — run queries, manage tables, and explore schemas.', githubUrl: 'https://github.com/clickhouse/mcp-clickhouse', npmPackage: '@clickhouse/mcp', pyPackage: null, homeUrl: null, author: 'ClickHouse', stars: 950, license: 'Apache-2.0', createdAt: new Date().toISOString(), lastUpdated: new Date().toISOString(), transports: ['http'], categories: ['database', 'analytics'], compatibility: { openai: 'native', anthropic: 'native', langchain: 'unknown', cursor: 'native' }, securityScore: null, installCommand: 'npx -y @clickhouse/mcp' },
  { slug: 'mcp-hello-world', name: 'Hello World MCP', shortDescription: 'Getting started example for MCP', description: 'Simple hello world MCP server for learning the Model Context Protocol. Demonstrates basic tool, resource, and prompt patterns.', githubUrl: 'https://github.com/modelcontextprotocol/create-mcp-server', npmPackage: 'create-mcp-server', pyPackage: null, homeUrl: null, author: 'Anthropic', stars: 3500, license: 'MIT', createdAt: new Date().toISOString(), lastUpdated: new Date().toISOString(), transports: ['stdio'], categories: ['reference', 'learning'], compatibility: { openai: 'unknown', anthropic: 'native', langchain: 'unknown', cursor: 'adapter' }, securityScore: null, installCommand: 'npx -y create-mcp-server' },
  { slug: 'mcp-mongodb', name: 'MongoDB MCP', shortDescription: 'MongoDB document database operations', description: 'MCP server for MongoDB — query documents, manage collections, and run aggregations.', githubUrl: 'https://github.com/mongodb/mcp-mongodb', npmPackage: '@mongodb/mcp', pyPackage: null, homeUrl: null, author: 'MongoDB', stars: 2100, license: 'MIT', createdAt: new Date().toISOString(), lastUpdated: new Date().toISOString(), transports: ['http'], categories: ['database', 'backend'], compatibility: { openai: 'native', anthropic: 'native', langchain: 'unknown', cursor: 'native' }, securityScore: null, installCommand: 'npx -y @mongodb/mcp' },
  { slug: 'mcp-pulumi', name: 'Pulumi MCP', shortDescription: 'Infrastructure as code management', description: 'MCP server for Pulumi infrastructure as code — manage stacks, resources, and deployments.', githubUrl: 'https://github.com/pulumi/mcp-pulumi', npmPackage: '@pulumi/mcp', pyPackage: null, homeUrl: null, author: 'Pulumi', stars: 750, license: 'Apache-2.0', createdAt: new Date().toISOString(), lastUpdated: new Date().toISOString(), transports: ['http'], categories: ['infrastructure', 'devops'], compatibility: { openai: 'native', anthropic: 'native', langchain: 'unknown', cursor: 'native' }, securityScore: null, installCommand: 'npx -y @pulumi/mcp' },
  { slug: 'mcp-supavisor', name: 'Supavisor MCP', shortDescription: 'Database connection pooling management', description: 'MCP server for Supavisor database connection pooling — manage pools, tenants, and connections.', githubUrl: 'https://github.com/supabase/mcp-supavisor', npmPackage: '@supabase/mcp-supavisor', pyPackage: null, homeUrl: null, author: 'Supabase', stars: 600, license: 'Apache-2.0', createdAt: new Date().toISOString(), lastUpdated: new Date().toISOString(), transports: ['http'], categories: ['database', 'infrastructure'], compatibility: { openai: 'native', anthropic: 'native', langchain: 'unknown', cursor: 'native' }, securityScore: null, installCommand: 'npx -y @supabase/mcp-supavisor' },
  { slug: 'mcp-terraform', name: 'Terraform MCP', shortDescription: 'Terraform infrastructure management', description: 'MCP server for Terraform — manage infrastructure, run plans, and apply configurations.', githubUrl: 'https://github.com/hashicorp/mcp-terraform', npmPackage: '@hashicorp/mcp-terraform', pyPackage: null, homeUrl: null, author: 'HashiCorp', stars: 1800, license: 'MIT', createdAt: new Date().toISOString(), lastUpdated: new Date().toISOString(), transports: ['http'], categories: ['infrastructure', 'devops'], compatibility: { openai: 'native', anthropic: 'native', langchain: 'unknown', cursor: 'native' }, securityScore: null, installCommand: 'npx -y @hashicorp/mcp-terraform' },
];

export async function handleSeed(request: Request, env: Env): Promise<Response> {
  const apiKey = request.headers.get('x-api-key');
  if (apiKey !== 'dev-seed-key') {
    return new Response(JSON.stringify({ error: 'Unauthorized' }), {
      status: 401,
      headers: { 'content-type': 'application/json' }
    });
  }

  const body = await request.json().catch(() => ({})) as { force?: boolean; tools?: any[] };
  const force = body.force === true;

  const hasTools = body.tools && body.tools.length > 0;

  if (force) {
    await env.DB.exec('DELETE FROM tools; DELETE FROM scan_results;');
  }

  const toolsToInsert = body.tools || SEED_TOOLS;
  const now = new Date().toISOString();

  let inserted = 0;
  const insertStmt = env.DB.prepare(
    `INSERT OR IGNORE INTO tools (id, slug, name, description, short_description, github_url, npm_package, py_package, home_url, author, stars, license, transports, categories, compatibility, install_command, created_at, last_updated) 
     VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`
  );

  for (const tool of toolsToInsert) {
    const id = crypto.randomUUID();
    await insertStmt.bind(
      id, tool.slug, tool.name, tool.description, tool.shortDescription,
      tool.githubUrl, tool.npmPackage || null, tool.pyPackage || null, tool.homeUrl || null,
      tool.author, tool.stars || 0, tool.license || null,
      JSON.stringify(tool.transports || ['stdio']), JSON.stringify(tool.categories || []),
      JSON.stringify(tool.compatibility || {}), tool.installCommand || '',
      tool.createdAt || now, tool.lastUpdated || now
    ).run();
    inserted++;
  }

  return new Response(JSON.stringify({
    message: 'Database seeded successfully',
    count: inserted,
    categories: [...new Set(SEED_TOOLS.flatMap(t => t.categories))]
  }), { headers: { 'content-type': 'application/json' } });
}
